# Generated by Django 3.1.4 on 2020-12-27 10:34

import apps.core.models
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.CharField(blank=True, default=apps.core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=96, verbose_name='Name')),
                ('terms', models.CharField(choices=[('NET7', 'Net 7 Days'), ('NET10', 'Net 10 Days'), ('NET21', 'Net 21 Days'), ('NET30', 'Net 30 Days'), ('EOM', 'End-of-Month'), ('15MFI', '15th MFI'), ('2/10NET30', 'Net 30, 2% Disc./Net 10'), ('UNSPECIFIED', 'Terms Not Specified')], default='UNSPECIFIED', max_length=32, verbose_name='Terms')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('state', django_fsm.FSMField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DISQUALIFIED', 'Disqualifed'), ('NAN', 'No Approval Necessary'), ('LAPSED', 'Lapsed')], default='PENDING', max_length=50, verbose_name='Status')),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('change_vendor_status', 'Can change status of vendor')],
                'get_latest_by': ['version'],
            },
        ),
        migrations.CreateModel(
            name='VendorOrder',
            fields=[
                ('id', models.CharField(blank=True, default=apps.core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('invoice_id', models.CharField(blank=True, max_length=48, null=True, verbose_name='Vendor Invoice Number')),
                ('purchasing_reference', models.CharField(blank=True, max_length=48, null=True, verbose_name='Purchasing Reference')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Invoice Total')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date placed')),
                ('date_delivery_scheduled', models.DateTimeField(verbose_name='Scheduled Delivery Date')),
                ('date_delivery_actual', models.DateTimeField(verbose_name='Actual Delivery Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to='purchasing.vendor')),
            ],
            options={
                'ordering': ['-date_delivery_scheduled'],
                'get_latest_by': ['date'],
            },
        ),
        migrations.CreateModel(
            name='VendorOrderLine',
            fields=[
                ('id', models.CharField(blank=True, default=apps.core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Unit Price')),
                ('extension', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Extension')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='materials.input')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.unitmeasurement')),
                ('vendor_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.vendororder')),
            ],
            options={
                'ordering': ['input'],
            },
        ),
        migrations.CreateModel(
            name='VendorCatalog',
            fields=[
                ('id', models.CharField(blank=True, default=apps.core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('vendor_item_number', models.CharField(max_length=32)),
                ('input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogs', to='materials.input')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogs', to='purchasing.vendor')),
            ],
            options={
                'get_latest_by': ['input'],
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='inputs',
            field=models.ManyToManyField(related_name='vendors', through='purchasing.VendorCatalog', to='materials.Input'),
        ),
    ]
