# Generated by Django 3.1.4 on 2020-12-27 10:34

import apps.core.models
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.CharField(blank=True, default=apps.core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('state', django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('AWAITING', 'Awaiting Approval'), ('RETURNED', 'Returned for Revisions'), ('APPROVED', 'Approved'), ('SUPERSEDED', 'Superseded'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=50, verbose_name='Status')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_of_materials', to='materials.material')),
            ],
            options={
                'verbose_name_plural': 'Bills of materials',
                'ordering': ['material', 'version'],
                'permissions': [('change_bom_status', 'Can change status of BOM'), ('submit_bom_for_approval', 'Can submit BOM for approval')],
                'get_latest_by': ['version'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(blank=True, default=apps.core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=32, null=True, verbose_name='Team name')),
                ('slug', models.SlugField(blank=True, max_length=32, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterialsYield',
            fields=[
                ('id', models.CharField(blank=True, default=apps.core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('quantity_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('quantity_volume', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('quantity_each', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('note_each', models.CharField(blank=True, max_length=64, null=True)),
                ('bill_of_materials', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yields', to='production.billofmaterials')),
                ('unit_each', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.unitmeasurement')),
                ('unit_volume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.unitmeasurement')),
                ('unit_weight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.unitmeasurement')),
            ],
            options={
                'verbose_name_plural': 'Bill of materials yields',
                'ordering': ['bill_of_materials__material'],
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterialsNote',
            fields=[
                ('id', models.CharField(blank=True, default=apps.core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('note', models.TextField()),
                ('bill_of_materials', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='production.billofmaterials')),
            ],
            options={
                'verbose_name_plural': 'Bill of materials notes',
                'ordering': ['bill_of_materials__material'],
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterialsLine',
            fields=[
                ('id', models.CharField(blank=True, default=apps.core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=8)),
                ('note', models.CharField(blank=True, max_length=32, null=True)),
                ('bill_of_materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.billofmaterials')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='materials.material')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unitmeasurement')),
            ],
            options={
                'verbose_name_plural': 'Bill of materials lines',
                'ordering': ['sequence', 'material'],
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterialsCharacteristics',
            fields=[
                ('id', models.CharField(blank=True, default=apps.core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('temperature_preparation', models.CharField(blank=True, choices=[('HOT', 'Hot'), ('AMBIENT', 'Ambient'), ('COLD', 'Cold')], max_length=8, null=True)),
                ('temperature_storage', models.CharField(blank=True, choices=[('HOT', 'Hot'), ('AMBIENT', 'Ambient'), ('COLD', 'Cold')], max_length=8, null=True)),
                ('temperature_service', models.CharField(blank=True, choices=[('HOT', 'Hot'), ('AMBIENT', 'Ambient'), ('COLD', 'Cold')], max_length=8, null=True)),
                ('note_production', models.TextField(blank=True, null=True, verbose_name='Production Notes')),
                ('total_active_time', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True)),
                ('total_inactive_time', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True)),
                ('staff_count', models.PositiveSmallIntegerField(default=0)),
                ('note_labor', models.TextField(blank=True, null=True, verbose_name='Labor Notes')),
                ('bill_of_materials', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='production.billofmaterials')),
            ],
            options={
                'verbose_name_plural': 'Bill of materials characteristics',
                'ordering': ['bill_of_materials__material'],
            },
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_of_materials', to='production.team'),
        ),
        migrations.CreateModel(
            name='BillOfMaterialsProcedure',
            fields=[
                ('id', models.CharField(blank=True, default=apps.core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('procedure', models.TextField()),
                ('language', models.CharField(choices=[('eng', 'English'), ('esp', 'Español'), ('fra', 'Français')], default='eng', max_length=3, verbose_name='Language')),
                ('bill_of_materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='production.billofmaterials')),
            ],
            options={
                'verbose_name_plural': 'Bill of materials procedures',
                'ordering': ['bill_of_materials', 'language'],
                'unique_together': {('bill_of_materials', 'language')},
            },
        ),
    ]
