# Generated by Django 3.1.4 on 2020-12-27 10:34

import apps.core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitMeasurement',
            fields=[
                ('id', models.CharField(blank=True, default=apps.core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Name')),
                ('symbol', models.CharField(max_length=9, verbose_name='Symbol')),
                ('unit_type', models.CharField(choices=[('WEIGHT', 'Weight'), ('VOLUME', 'Volume'), ('EACH', 'Each'), ('MISC', 'Miscellaneous'), ('INVENTORY', 'Inventory')], default='WEIGHT', max_length=12, verbose_name='Type')),
            ],
            options={
                'ordering': ['unit_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryEvent',
            fields=[
                ('id', models.CharField(blank=True, default=apps.core.models.generate_ulid, editable=False, max_length=26, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('event_type', models.CharField(choices=[('PRODUCED', 'Produced'), ('PLANNED', 'Planned'), ('ORDERED', 'Ordered'), ('RECEIVED', 'Received'), ('FULFILLED', 'Fulfilled'), ('ADJUSTED', 'Adjusted'), ('FORECASTED', 'Forecasted')], default='PRODUCED', max_length=12)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.unitmeasurement')),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': ['id'],
            },
        ),
    ]
